#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# nethserver-docker-update event
#

event_templates('nethserver-docker-update', qw(
  /etc/sysconfig/docker-network
));

event_services('nethserver-docker-update', qw(
  docker restart
));

#
# docker-fw-adjust event
#

event_templates('docker-fw-adjust', qw(
  /etc/shorewall/rules
));

event_services('docker-fw-adjust', qw(
  shorewall restart
));
