#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# event nethserver-docker-update event
#
event_templates('nethserver-docker-update', qw(
    /etc/docker/docker.conf
    /etc/nethserver/eorepo.conf
));
event_actions('nethserver-docker-update', qw(
    initialize-default-databases   00
    nethserver-docker-create-network 20
    nethserver-docker-create-portainer 20
    nethserver-docker-create-aeria 20
));
event_services('nethserver-docker-update', qw(
    docker restart
    httpd-admin reload
));

#
# event nethserver-docker-plugin-update event
#
event_actions('nethserver-docker-plugin-update', qw(
    initialize-default-databases   00
    nethserver-docker-upgrade-plugin 20
));
