#!/bin/bash

macVlanNetwork=$(/usr/sbin/e-smith/db configuration getprop docker macVlanNetwork)
macVlanNic=$(/usr/sbin/e-smith/db configuration getprop docker macVlanNic)

if [[ -z $macVlanNetwork ]]; then
    exit 0
fi

if [[ -z $macVlanNic ]]; then
    exit 0
fi

#
# First delete macvlan0 
#
/usr/sbin/ip link delete macvlan0 &> /dev/null

#
# Create macvlan0
#
/usr/sbin/ip link add macvlan0 link $macVlanNic type macvlan mode bridge
/usr/sbin/ip addr add $macVlanNetwork dev macvlan0
/usr/sbin/ip link set macvlan0 up
