#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Check if aeria network does not exist and the bridge is set, install the net-dhcp plugin and create the docker aeria network
#

bridgeAeria=$(/sbin/e-smith/config getprop docker bridgeAeria)

if [[ -z ${bridgeAeria} ]]; then
    exit 0
fi

HasNetwork=$(docker network ls -f name=aeria -q)
if [[ $? != 0 ]]; then
    exit 1
fi

docker plugin install --grant-all-permissions devplayer0/net-dhcp

if [[ -n ${HasNetwork} ]]; then
    exit 0
fi

echo "[NOTICE] Creating the aeria Docker network..."
docker network create -d devplayer0/net-dhcp:latest --ipam-driver null -o bridge=${bridgeAeria} aeria
