#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Create the Portainer container instance
#

status=$(/sbin/e-smith/config getprop docker status)
portainer=$(/sbin/e-smith/config getprop portainer status)
IpAddress=172.28.255.254

if [[ ${status} != enabled ]]; then
    exit 0
fi

if [[ ${portainer} != enabled ]]; then
    exit 0
fi

HasPortainer=$(docker ps -f name=portainer -q -a)

if [[ $? != 0 ]]; then
    exit 1
fi

if [[ -n ${HasPortainer} ]]; then
    exit 0
fi

docker run --detach \
    --restart always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/nethserver/portainer:/data \
    --name portainer \
    --hostname portainer \
    --network aqua \
    --ip ${IpAddress} \
    portainer/portainer-ce \
    -H unix:///var/run/docker.sock
