#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Upgrade net-dhcp plugin if aeria is enabled and bridge exists
#

bridge=$(/sbin/e-smith/config getprop docker bridge)

if [[ -z ${bridge} ]]; then
    exit 0
fi

docker plugin disable devplayer0/net-dhcp;docker plugin rm devplayer0/net-dhcp;docker plugin install --grant-all-permissions devplayer0/net-dhcp
