#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

macVlanNic=$(/usr/sbin/e-smith/db configuration getprop docker macVlanNic)
macVlanGateway=$(/usr/sbin/e-smith/db configuration getprop docker macVlanGateway)
macVlanLocalNetwork=$(/usr/sbin/e-smith/db configuration getprop docker macVlanLocalNetwork)
bridgeAeria=$(/sbin/e-smith/config getprop docker bridgeAeria)

# Check if macvlan network does not exist, and attempt to create it as necessariy
#

status=$(/sbin/e-smith/config getprop docker status)

if [[ ${status} != enabled ]]; then
    exit 0
fi

if ! systemctl is-active -q docker; then
    echo "[WARNING] Attempt to start docker"
    systemctl start docker
fi


HasNetwork=$(docker network ls -f name=macvlan -q)
if [[ $? != 0 ]]; then
    exit 1
fi

if [[ -n ${HasNetwork} ]]; then
    exit 0
fi

if [[ -z $macVlanGateway ]]; then
    exit 0
fi

if [[ -z $macVlanLocalNetwork ]]; then
    exit 0
fi

if [[ -z $macVlanNic ]]; then
    exit 0
fi

# We want a bridge to create macvlan on it, we verify before
nicExist=$(/usr/sbin/e-smith/db networks get $macVlanNic)
if [[ -z $nicExist ]];then
    exit 0
fi

isBridge=$(/usr/sbin/e-smith/db networks gettype $macVlanNic)
if [[ $isBridge != 'bridge' ]];then
    echo "The nic is not a bridge, macvlan cannot be created"
    exit 0
fi

if [[ ${bridgeAeria} == ${macVlanNic} ]]; then
    echo "[NOTICE] The macvlan and aeria network cannot share the same bridge"
    exit 0
fi

/usr/bin/docker network create --driver=macvlan --gateway=${macVlanGateway} --subnet=${macVlanLocalNetwork} -o parent=${macVlanNic} macvlan
